import type { FieldAttribute, FieldType } from "./db.ts"

export interface ColumnInfo {
  name: string
  dataType: string
}

export interface TableInfo {
  name: string
  columns: ColumnInfo[]
}

export type IdGenerationStrategy = "string" | "number" | "uuid" | "serial"

export interface ColumnDefinition {
  type: string
  notNull: boolean
  primaryKey?: boolean
  autoIncrement?: boolean
  unique?: boolean
  references?: { table: string; field: string }
  /**
   * Field-level hints that may influence DDL beyond `type`. Carried
   * through so adapter migrators that branch on these (e.g. mysql
   * varchar sizing) keep working under the generic engine.
   */
  bigint?: boolean
  sortable?: boolean
  /**
   * A raw SQL expression to use as a server-side default
   * (e.g. `CURRENT_TIMESTAMP`, `gen_random_uuid()`). Mutually exclusive
   * with `autoIncrement`.
   */
  defaultExpr?: string
}

export interface IndexDefinition {
  table: string
  field: string
  unique: boolean
}

export interface MigratorOptions {
  useNumberId: boolean
  /**
   * Id generation strategy resolved from the user config.
   *  - "string" (default): the engine generates a UUID-string in JS
   *  - "number":           autoincrement integer PK (legacy useNumberId=true)
   *  - "uuid":             database-side UUID via gen_random_uuid()
   *  - "serial":           Postgres GENERATED BY DEFAULT AS IDENTITY
   */
  idStrategy: IdGenerationStrategy
}

/**
 * Adapter-supplied migrator. Each adapter that supports schema migrations
 * implements this to introspect and emit DDL using its own native API.
 *
 * Adapters that don't support migrations (mongodb, memory, prisma, drizzle)
 * may simply not provide one; the engine reports a clear error in that case.
 */
export interface AdapterMigrator {
  introspect: () => Promise<TableInfo[]>
  createTable: (
    table: string,
    idColumn: ColumnDefinition,
    fields: Record<string, ColumnDefinition>,
  ) => Promise<void>
  addColumn: (table: string, name: string, column: ColumnDefinition) => Promise<void>
  /**
   * Emit `CREATE [UNIQUE] INDEX <table>_<field>_idx ON <table>(<field>)`
   * for fields marked with `index: true`. Migration engine defers all
   * index creation until after CREATE TABLE / ADD COLUMN have run.
   */
  createIndex?: (index: IndexDefinition) => Promise<void>
  resolveType: (field: FieldAttribute, fieldName: string, options: MigratorOptions) => string
  matchType: (columnDataType: string, fieldType: FieldType) => boolean
  compileCreateTable?: (
    table: string,
    idColumn: ColumnDefinition,
    fields: Record<string, ColumnDefinition>,
  ) => string
  compileAddColumn?: (table: string, name: string, column: ColumnDefinition) => string
  compileCreateIndex?: (index: IndexDefinition) => string
}
