name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"

  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 👀 Lint
        run: pnpm lint

      - name: 🔍 Typecheck
        run: pnpm typecheck

      - name: 🚀 Build
        run: pnpm build

      - name: 🐳 Start Docker Containers
        run: |
          docker compose up -d
          sleep 10

      - name: 🧪 Test with coverage
        run: pnpm test:coverage
        env:
          MAILCRAB_HOST: localhost
          MAILCRAB_SMTP_PORT: 1025
          MAILCRAB_UI_PORT: 1080

      - name: 📝 Upload coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2

      - name: 🛑 Stop Docker Containers
        if: always()
        run: docker compose down
